### ISSUE TITLE
Raspberry Pico W

### ISSUE THREAD

**Issue by sstaub** [maxgerhardt/platform-raspberrypi#10]
Support for Raspberry Pi Pico W.

**Comment by maxgerhardt** [comment]
This is currently added but untested by me on real hardware. The https://github.com/maxgerhardt/platform-raspberrypi/tree/develop/examples/arduino-wifi-scan compiles with the latest platform version.

I preordered my Pico W and am expecting it soon.

**Comment by sstaub** [comment]
I will try tomorrow.

**Comment by maxgerhardt** [comment]
Due to a linking bug that will be fixed in [this PR](https://github.com/earlephilhower/arduino-pico/pull/696), you currently have to call the WiFi init function manually, but then it was [reported to work](https://github.com/earlephilhower/arduino-pico/issues/66#issuecomment-1191302275)

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/maxgerhardt/platform-raspberrypi/commit/bd2f3e756ba7340150f2bebc2d46110988243018, so after a `pio pkg update -g -p raspberrypi` you should be good to go.

**Comment by sstaub** [comment]
Tested with wifi-scan example and works fine.
