### ISSUE TITLE
Variables shared between cores

### ISSUE THREAD

**Issue by MadTooler** [maxgerhardt/platform-raspberrypi#20]
This is more of a question than an issue at this time.

When accessing the same variables from both active cores on the pico, does the platform either auto set the variables to volatile or already handle them in a manner that corruption is not an issue if they are not declared as volatile?

Thanks.

**Comment by maxgerhardt** [comment]
I'm pretty sure the C/C++ compiler doesn't do that automatically for you. You'd have to use a mutual exclusion method for changing them concurrently.

**Comment by MadTooler** [comment]
OK.  Thanks.
