### ISSUE TITLE
RPi Pico W build fails when using api services in ESPHome

### ISSUE THREAD

**Issue by THorst92** [maxgerhardt/platform-raspberrypi#23]
Hi,

I am not sure if this might be also a problem for this repository.
I found an issue while using the RPi Pico in ESPHome with the api services and created the following bug: esphome/issues#4160
Since the platformio package is mentioned in the failure messages, I thought to post it also here.

Could anyone maybe help me?

**Comment by maxgerhardt** [comment]
This is a fault in ESPHome sources, probably a missing implementation for the RP2040, just like https://community.platformio.org/t/error-ld-returned-1-exit-status-remote-transmitter/32101.

Aka, not a problem of this repo.

I can only advise you to look at the source code you're building and where those
```cpp
long esphome::api::get_execute_arg_value<long>(esphome::api::ExecuteServiceArgument const&)

esphome::api::UserServiceBase<long>::execute_service(esphome::api::ExecuteServiceRequest const&)
```
etc functions are that you're missing.

**Comment by THorst92** [comment]
Thanks for the hint! I think I got the problem and updated esphome/issues#4160.
