### ISSUE TITLE
ADCInput missing?!

### ISSUE THREAD

**Issue by sreimchen** [maxgerhardt/platform-raspberrypi#24]
Hi Max,

im using this repo with PlatformIO. But anyhow it is missing the ADCInput.h that is found in Earle's core see here: https://github.com/earlephilhower/arduino-pico/tree/master/libraries/ADCInput

I get an include error and didn't find the corresponding header in the core's files:
![image](https://user-images.githubusercontent.com/33686223/221560014-5c3a6bc3-a099-4662-b3f8-9d9bbc6786a6.png)
![image](https://user-images.githubusercontent.com/33686223/221560585-a8e11aaf-2a2d-4fb1-9020-1ecdef54cab8.png)

Do you have any idea? Any help is very much appreciated because I'm currently depending on this to work...

**Comment by sreimchen** [comment]
platform.io:
![image](https://user-images.githubusercontent.com/33686223/221560919-b3a2934f-5731-4e71-b637-dba6c199c3c4.png)

**Comment by sreimchen** [comment]
I guess the fork is not using the latest core? Anyhow, got it fixed by reading another issue here on this repo. Sorry, for taking your time.

Fixed by adding to the platformio.ini:
platform_packages = framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git

**Comment by maxgerhardt** [comment]
Yes, the core reference is not always up to date since I want to make sure it compiles and works file when I update. Will be updated soon after I verify bluetooth examples from SDK 1.5 upgrade work.

**Comment by sreimchen** [comment]
That makes sense, thank you for your work by the way :)

**Comment by maxgerhardt** [comment]
Arduino-Pico was updated in 090343e4478f749da5347487ca42c231df75aab3.
