### ISSUE TITLE
Device is not properly unmounted after flashing

### ISSUE THREAD

**Issue by N0ury** [maxgerhardt/platform-raspberrypi#30]
I'm on MacOS Big sur.
When flashing is finished I have a message saying that device RPI-RP2 must be ejected before disconnecting.
I have seen that a filesystem named RPI-RP2 is mounted during flashing.
I think it needs to be unmounted when flashing is finished.

**Comment by maxgerhardt** [comment]
Standard flashing method with picotool is the same as used in https://github.com/platformio/platform-raspberrypi, please file issue against that repo.
