### ISSUE TITLE
HELP 

### ISSUE THREAD

**Issue by PabloOyarzo** [maxgerhardt/platform-raspberrypi#31]
I'm using Windows 10, Pi Pico, VS Code and Platform IO (latest versions)

Using the the stock platform for the Pi on PIO was giving me the error of  reseting the connectiong of the Pi and opening as a drive device and platformio trying to upload .elf file. 

After watching your PR and all the drama I tried to change the platform to your Fork. but ive been trying since yesterday even deleting the C:/user/.platformio/tmp file to force it to download everything again. 

This is the error appearing

 Submodule 'hidapi' (https://github.com/signal11/hidapi) registered for path 'pico-sdk/lib/tinyusb/tools/uf2/hidapi'

Cloning into 'C:/Users/[USER]/.platformio/.cache/tmp/pkg-installing-861qm122/pico-sdk/lib/tinyusb/tools/uf2/hidapi'...

Submodule path 'pico-sdk/lib/tinyusb/tools/uf2/hidapi': checked out 'a6a622ffb680c55da0de787ff93b80280498330f'
fatal: Unable to checkout '17761f5cf9dbbf2dcf665b7c04934188add20082' in submodule path 'pico-sdk/lib/tinyusb/hw/mcu/wch/ch32v307'

fatal: Failed to recurse into submodule path 'pico-sdk/lib/tinyusb'

From https://github.com/earlephilhower/bearssl-esp8266
 * branch            f294aa022f82833941ffdf3b0f306c2072e3a26c -> FETCH_HEAD

Submodule path 'tools/libbearssl/bearssl': checked out 'f294aa022f82833941ffdf3b0f306c2072e3a26c'
Submodule path 'tools/pyserial': checked out '0e7634747568547b8a7f9fd0c48ed74f16af4b23'
fatal: Failed to recurse into submodule path 'pico-sdk'

Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/earlephilhower/arduino-pico.git', 'C:\\Users\\[USER]\\.platformio\\.cache\\tmp\\pkg-installing-861qm122']

**Comment by maxgerhardt** [comment]
>fatal: Failed to recurse into submodule path 'pico-sdk/lib/tinyusb'

You must follow https://arduino-pico.readthedocs.io/en/latest/platformio.html#important-steps-for-windows-users-before-installing
