### ISSUE TITLE
Higher version needed on __GNUC__

### ISSUE THREAD

**Issue by Dollar0712** [maxgerhardt/platform-raspberrypi#37]
Hi, 
I am new to platformio development.
One of the important libraries needs __GNUC__ version to be greater than 11.
Is there a way that I can change it?
Thank you

**Comment by maxgerhardt** [comment]
There are issues with GDB under Windows holding back this update, see https://github.com/earlephilhower/arduino-pico/issues/1681.

If you don't care about debugging, you can use the new toolchain at any time, see https://community.platformio.org/t/how-to-upgrade-gnuc-version-of-pico-using-platformio/35624.
