### ISSUE TITLE
error: 'alarm_pool_get_default' was not declared in this scope;

### ISSUE THREAD

**Issue by rondlh** [maxgerhardt/platform-raspberrypi#45]
I'm playing around with the alarm_pools on a Pico, but the command "alarm_pool_get_default()" seems to be missing.

**main.cpp**
```
#include <Arduino.h>
alarm_pool_t* HAL_timer_pool_0;
alarm_pool_t* HAL_timer_pool_1;
alarm_pool_t* HAL_timer_pool_2;
alarm_pool_t* HAL_timer_pool_3;

setup() {
  HAL_timer_pool_0 = alarm_pool_create(0, 6);
  HAL_timer_pool_1 = alarm_pool_create(1, 6);
  HAL_timer_pool_2 = alarm_pool_create(2, 6);
  HAL_timer_pool_3 = alarm_pool_get_default();
}

loop() {
}
```

**platformio.ini**
```
[env]
platform = raspberrypi
framework = arduino
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
```

Any solutions?

**Comment by maxgerhardt** [comment]
You don't set the special flags or the right board defnition to use the Arduino-Pico core, so you'll be using th ArduinoCore-mbed. Which wouldn't need my fork of the raspberrypi platform at all.

So if it compiles in Arduino-Pico, just use `board = rpipico` instead, or see https://arduino-pico.readthedocs.io/en/latest/platformio.html#examples
