### ISSUE TITLE
web server not working on Raspberry Pi Pico W web_server:   port: 80

### ISSUE THREAD

**Issue by RajivCodeLab** [maxgerhardt/platform-raspberrypi#62]
Not able to run the web server on Raspberry Pi Pico W whereas the same code running fine in ESP.

web_server:
  port: 80

![image](https://github.com/maxgerhardt/platform-raspberrypi/assets/5146682/72351804-72bb-4bd2-9a73-28648643a9be)

**Comment by maxgerhardt** [comment]
That's an issue of the programming esphome, not this platform. This platform supports the Arduino-Pico core which can very well host a HTTP server on the Pico W.

https://github.com/earlephilhower/arduino-pico/blob/master/libraries/WebServer/examples/HelloServer/HelloServer.ino

Reopen issue in esphome.
