### ISSUE TITLE
RISCV Branch deleted - Platform no longer builds

### ISSUE THREAD

**Issue by 814k31** [maxgerhardt/platform-raspberrypi#81]
The Arduino pico branch that this platform relies on has been deleted and merged to master

https://github.com/earlephilhower/arduino-pico/pull/2491

This line needs to be updated
https://github.com/maxgerhardt/platform-raspberrypi/blob/a7eddaaf010b973987b013d3f7380891e9afd449/platform.json#L54

I am receiving the error:
![image](https://github.com/user-attachments/assets/28aa79f5-ebb0-40df-bcc7-20c5fc293c0e)

**Comment by maxgerhardt** [comment]
Fixed in 1177f9c9029080d1a1f6ffa27028580c7147873f
