### ISSUE TITLE
Feature Request: Add Raspberry Pi Pico2W board definition

### ISSUE THREAD

**Issue by tyeth** [maxgerhardt/platform-raspberrypi#86]
Hey, thanks for the great work!

Just raising a quick issue to request the new pico2w board definition be added.

~~I might have a go presuming it's similar to the picow + pimoroni 2w.~~
I've used the pimoroni definition as a base, and used the rpipicow as a reference to update that base definition. Possibly extra things needed, but it builds, and connects to wifi and transmits data (Adafruit WipperSnapper firmware testing).

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/maxgerhardt/platform-raspberrypi/commit/08180f6315b38cbb72575307bdd6f156f8996427

**Comment by tyeth** [comment]
You legend, thanks @maxgerhardt
